---
- name: Check if XOA image is already downloaded
  stat:
    path: "{{ download_dest }}"
  register: file_status
  delegate_to: localhost

- name: Download XOA image
  block:
    - name: Show download start message
      debug:
        msg: "Starting download of XOA image from {{ download_url }}"

    - name: Download XOA image
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_dest }}"
      delegate_to: localhost

    - name: Show download completion message
      debug:
        msg: "Download completed successfully"
  when: not file_status.stat.exists

- name: Show file status
  debug:
    msg: "XOA image file: {% if file_status.stat.exists %}already exists{% else %}downloaded{% endif %}"
    verbosity: 1

- name: Upload XOA OVA to XCP-ng
  command: >
    scp {{ download_dest }} {{ ansible_user }}@{{ ansible_host }}:{{ remote_ova_path }}
  delegate_to: localhost

- name: Import XOA VM
  raw: cat {{ remote_ova_path }}| zcat | xe vm-import filename=/dev/stdin sr-uuid={{ storage_uuid }}
  register: vm_import_response

- name: Extract VM UUID
  ansible.builtin.set_fact:
    vm_uuid: "{{ vm_import_response.stdout | replace('\r\n', '') }}"

- name: Debug import
  debug:
    msg: "Import VM: {{ vm_uuid }} "

