---
# Network configuration
xoa_network_interface: "eth0"

# XOA image configuration
download_url: "https://xo-image.yawn.fi/downloads/image.xva.gz"
download_dest: "image.xva.gz"
remote_ova_path: "image.xva.gz"

# Network configuration must be defined in inventory or playbook vars:
# xoa_ipaddress: "192.168.1.3"     # Required
# xoa_netmask: "255.255.255.0"     # Required
# xoa_gateway: "192.168.1.1"       # Required
# xoa_dns: "8.8.8.8"               # Optional, defaults to gateway if not set
